export const RESET_PASSWORD_LEVEL = "RESET_PASSWORD_LEVEL";
export const RESET_PASSWORD_SET = "RESET_PASSWORD_SET";
export const RESET_PASSWORD_SET_LOGIN = "RESET_PASSWORD_SET_LOGIN";
export const RESET_PASSWORD_CHECK_TOKEN = "RESET_PASSWORD_CHECK_TOKEN";
